name: soundfloor
favicon: null
layout_spectrum: 0.08265602542087436
typography_spectrum: 0.2739778847899288
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
  brandStrength: 0.875
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
